spring:
  application:
    name: beer-catalog-service

server:
  port: 8080

eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
   instance:
      hostname: localhost
