spring:
  application:
    name: edge-service

server:
  port: 8081

eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
   instance:
      hostname: localhost
