spring:
  application:
    name: anotherService

server:
  port: 8767

eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
   instance:
      hostname: localhost
